Added Indonesian Translate
nlogozzo/NickvisionMoney pull request #164
Opened 2023-01-04 16:59 UTC by Krindog7337

2023-01-04 17:53 UTC, fsobolev requested changes

2023-01-04 17:53 UTC, fsobolev commented on NickvisionMoney.Shared/Resources/Strings.id.resx
> +		<value>Atur Ulang FIlter Tanggal</value>
I assume there's a typo ("F**I**lter")

2023-01-04 17:53 UTC, fsobolev commented on NickvisionMoney.Shared/Resources/Strings.id.resx
> +		<value>Developer:&#xA;{0}&#xA;&#xA;Designers:&#xA;{1}&#xA;&#xA;Artists:&#xA;{2}&#xA;&#xA;Translators:&#xA;{3}</value>
Not translated

2023-01-04 17:53 UTC, fsobolev commented on NickvisionMoney.Shared/Resources/Strings.id.resx
> +		<value>Rekening Uang Nickvision</value>
See https://github.com/nlogozzo/NickvisionMoney/pull/152#discussion_r1059423855

2023-01-04 17:53 UTC, fsobolev commented on NickvisionMoney.Shared/Resources/Strings.id.resx
> +		<value>Rekening Uang (*.nmoney)</value>
Same as "NickvisionMoneyAccount", see https://github.com/nlogozzo/NickvisionMoney/pull/152#discussion_r1059423855

2023-01-05 13:15 UTC, fsobolev approved these changes

2023-01-05 14:59 UTC, nlogozzo approved these changes

2023-01-05 14:59 UTC, merged

2023-01-05 15:00 UTC, nlogozzo commented
Thanks for the translation!