WinUI - Spanish Docs
nlogozzo/NickvisionMoney pull request #219
Opened 2023-01-16 17:52 UTC by fsobolev

[Preview](https://htmlpreview.github.io/?https://github.com/nlogozzo/NickvisionMoney/blob/028710c8ed10b387e2f72fbfc8e88998c80ead46/NickvisionMoney.Shared/Docs/html/es/index.html)

I changed the code to open correct link in `PreferencesPage.xaml.cs` and can't test it, but I guess it works as expected.

2023-01-16 19:15 UTC, fsobolev commented
Also updated `translate_meta.py` script to translate summary (as I mentioned [here](https://github.com/nlogozzo/NickvisionMoney/pull/217#discussion_r1071452684)).

2023-01-17 01:19 UTC, nlogozzo requested changes

2023-01-17 01:19 UTC, nlogozzo commented on NickvisionMoney.WinUI/Views/PreferencesPage.xaml.cs
> +        if (availableTranslations.Contains(CultureInfo.CurrentCulture.TwoLetterISOLanguageName.ToString()))
`CultureInfo.CurrentCulture.TwoLetterISOLanguageName` is already a string, therefore the extra `ToString()` is not needed.

https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.twoletterisolanguagename?view=net-7.0

2023-01-17 01:30 UTC, nlogozzo approved these changes

2023-01-17 01:30 UTC, merged